Override __eq__ of ``FlowBase`` Class to compare two flows
kytos/of_core pull request #102
Opened 2020-12-10 14:33 UTC by cmagnobarbosa

### :octocat: Are you working on some issue? Identify the issue!

Fix #101 

### :bookmark_tabs: Description of the Change

Override ``__eq__`` of ``FlowBase`` Class to compare two ``flows``.

### :page_facing_up: Release Notes

- Override ``__eq__`` of ``FlowBase`` Class to compare two flows

2020-12-10 17:09 UTC, hdiogenes requested changes
I think this is the kind of change that begs for an unit test.

2020-12-10 17:09 UTC, hdiogenes commented on flow.py
> +                             'is not a FlowBase class')
There's a wrong assumption here that `self.__class__` will always be `FlowBase`. It'll be whatever class inherited from FlowBase (eg.: `v0x01.Flow`). Either you change the comparison to check just for FlowBase (and allow for comparing different classes of Flow, like comparing a v0x01 Flow against a v0x04) or you change the message to make it explicit that you won't allow comparing different versions of Flow (which I think makes more sense and suggested below). 

```suggestion
        if not isinstance(other, self.__class__):
            raise ValueError(f'Error comparing flows: {other} is not '
                             f'an instance of {self.__class__}')
```

2020-12-10 17:09 UTC, hdiogenes commented on flow.py
> +        return False
```suggestion
        return self.as_dict(include_id=False) == other.as_dict(include_id=False)
```

2020-12-10 17:09 UTC, hdiogenes commented on flow.py
> +        include_id = False
```suggestion
```

2020-12-22 13:38 UTC, ajoaoff approved these changes

2020-12-22 16:23 UTC, rmotitsuki commented
One suggestion, add an inequality unit test just to make sure it's working too.

2020-12-22 17:46 UTC, hdiogenes commented on setup.cfg
> +--ignored-modules=napps.kytos.of_core
Does this really work as expected in a new line?

2020-12-22 19:18 UTC, josemauro commented
@rmotitsuki we already have a test called "test__eq__success_with_different_flows" that tests an inequality. 
Also, we have a "test__eq__fail" that tests the case where "__eq__" receives objects with different types.

2020-12-23 15:44 UTC, merged

2020-12-23 15:49 UTC, rmotitsuki commented
> @rmotitsuki we already have a test called "test__eq__success_with_different_flows" that tests an inequality.
> 
> https://github.com/kytos/of_core/blob/5536d7ff381c71462b5d4b9de754eb9ffc387fdc/tests/unit/test_flow.py#L130
> 
> 
> Also, we have a "test__eq__fail" that tests the case where "**eq**" receives objects with different types.
> https://github.com/kytos/of_core/blob/5536d7ff381c71462b5d4b9de754eb9ffc387fdc/tests/unit/test_flow.py#L171

@josemauro You test if the equality operator is False.
Inequality operator is the " != ". It should be fine in Python3, but is just another unit test to make sure everything is working.